/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  faker,
} from '@faker-js/faker'
import {
  HttpResponse,
  delay,
  http,
} from 'msw'

export const getRejectResponseMock = (): string => (faker.word.sample())

export const getAfterLoginResponseMock = (): string => (faker.word.sample())

export function getRejectMockHandler(overrideResponse?: string) {
  return http.post('*/api-v1/work/kratos/webhook/reject', async () => {
    await delay(1000)
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined ? overrideResponse : getRejectResponseMock()), {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
      },
    })
  })
}

export function getAfterLoginMockHandler(overrideResponse?: string) {
  return http.post('*/api-v1/work/kratos/webhook/logging-identity', async () => {
    await delay(1000)
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined ? overrideResponse : getAfterLoginResponseMock()), {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
      },
    })
  })
}
export function getKratosWebhookControllerMock() {
  return [
    getRejectMockHandler(),
    getAfterLoginMockHandler(),
  ]
}
