/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  faker,
} from '@faker-js/faker'
import {
  HttpResponse,
  delay,
  http,
} from 'msw'

export const getHealthcheckResponseMock = (): string => (faker.word.sample())

export function getExecuteMockHandler() {
  return http.post('*/api-v1/proxy/execute', async () => {
    await delay(1000)
    return new HttpResponse(null, {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
      },
    })
  })
}

export function getHealthcheckMockHandler(overrideResponse?: string) {
  return http.get('*/api-v1/proxy/healthcheck', async () => {
    await delay(1000)
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined ? overrideResponse : getHealthcheckResponseMock()), {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
      },
    })
  })
}
export function getProxyControllerMock() {
  return [
    getExecuteMockHandler(),
    getHealthcheckMockHandler(),
  ]
}
