/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  HttpResponse,
  delay,
  http,
} from 'msw'

export function getTestSessionBindingCleanerMockHandler() {
  return http.get('*/api-v2/test/test-kratos-session-binding-cleaner', async () => {
    await delay(1000)
    return new HttpResponse(null, {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
      },
    })
  })
}

export function getTestCleanerMockHandler() {
  return http.get('*/api-v2/test/test-cleaner', async () => {
    await delay(1000)
    return new HttpResponse(null, {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
      },
    })
  })
}

export function getTestChapterCleanerMockHandler() {
  return http.get('*/api-v2/test/test-chapter-cleaner', async () => {
    await delay(1000)
    return new HttpResponse(null, {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
      },
    })
  })
}
export function getTestControllerMock() {
  return [
    getTestSessionBindingCleanerMockHandler(),
    getTestCleanerMockHandler(),
    getTestChapterCleanerMockHandler(),
  ]
}
