/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UserGroupWithPermissions } from './userGroupWithPermissions'

export interface AddRemoveUserMultiGroupRes {
  EMAIL?: string
  GROUPS?: UserGroupWithPermissions[]
  ID?: number
  ROLE?: string
}
