/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface AddRemoveUserMultiGroupReq {
  GROUP_IDS?: number[]
  /** @minimum 1 */
  USER_ID?: number
}
