/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UserUpdatePassRes } from './userUpdatePassRes'

export interface AppResponseUserUpdatePassRes {
  DATA?: UserUpdatePassRes
  ERR_CODE?: string
  REASON?: string
  RESULT?: string
}
