/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { LogDtoRes } from './logDtoRes'

export interface AppResponseLogDtoRes {
  DATA?: LogDtoRes
  ERR_CODE?: string
  REASON?: string
  RESULT?: string
}
