/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { TextBoxDtoRes } from './textBoxDtoRes'

export interface AppResponseListTextBoxDtoRes {
  DATA?: TextBoxDtoRes[]
  ERR_CODE?: string
  REASON?: string
  RESULT?: string
}
