/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { AdminUpdatePassRes } from './adminUpdatePassRes'

export interface AppResponseAdminUpdatePassRes {
  DATA?: AdminUpdatePassRes
  ERR_CODE?: string
  REASON?: string
  RESULT?: string
}
