/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { TaskResItem } from './taskResItem'

export interface AppResponseTaskResItem {
  DATA?: TaskResItem
  ERR_CODE?: string
  REASON?: string
  RESULT?: string
}
