/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { GetComicIdRes } from './getComicIdRes'

export interface AppResponseGetComicIdRes {
  DATA?: GetComicIdRes
  ERR_CODE?: string
  REASON?: string
  RESULT?: string
}
