/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { CheckNameExistRes } from './checkNameExistRes'

export interface AppResponseCheckNameExistRes {
  DATA?: CheckNameExistRes
  ERR_CODE?: string
  REASON?: string
  RESULT?: string
}
