/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { CreateIdentityRes } from './createIdentityRes'

export interface AppResponseCreateIdentityRes {
  DATA?: CreateIdentityRes
  ERR_CODE?: string
  REASON?: string
  RESULT?: string
}
