/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Res } from './res'

export interface AppResponseRes {
  DATA?: Res
  ERR_CODE?: string
  REASON?: string
  RESULT?: string
}
