/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { CrawlSiteDto } from './crawlSiteDto'

export interface AppResponseListCrawlSiteDto {
  DATA?: CrawlSiteDto[]
  ERR_CODE?: string
  REASON?: string
  RESULT?: string
}
