/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { GetChapterDetailRes } from './getChapterDetailRes'

export interface AppResponseGetChapterDetailRes {
  DATA?: GetChapterDetailRes
  ERR_CODE?: string
  REASON?: string
  RESULT?: string
}
