/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { TranslateEngineEntity } from './translateEngineEntity'

export interface AppResponseListTranslateEngineEntity {
  DATA?: TranslateEngineEntity[]
  ERR_CODE?: string
  REASON?: string
  RESULT?: string
}
