/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ChapterDetailRes } from './chapterDetailRes'

export interface AppResponseChapterDetailRes {
  DATA?: ChapterDetailRes
  ERR_CODE?: string
  REASON?: string
  RESULT?: string
}
