/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { AddRemoveUserMultiGroupRes } from './addRemoveUserMultiGroupRes'

export interface AppResponseAddRemoveUserMultiGroupRes {
  DATA?: AddRemoveUserMultiGroupRes
  ERR_CODE?: string
  REASON?: string
  RESULT?: string
}
