/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { DeleteRes } from './deleteRes'

export interface AppResponseDeleteRes {
  DATA?: DeleteRes
  ERR_CODE?: string
  REASON?: string
  RESULT?: string
}
