/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { DeleteIdentitiesRes } from './deleteIdentitiesRes'

export interface AppResponseDeleteIdentitiesRes {
  DATA?: DeleteIdentitiesRes
  ERR_CODE?: string
  REASON?: string
  RESULT?: string
}
