/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { GroupFilterRes } from './groupFilterRes'

export interface AppResponseListGroupFilterRes {
  DATA?: GroupFilterRes[]
  ERR_CODE?: string
  REASON?: string
  RESULT?: string
}
