/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { RedirectExportChapterInput } from './redirectExportChapterInput'

export interface AppResponseRedirectExportChapterInput {
  DATA?: RedirectExportChapterInput
  ERR_CODE?: string
  REASON?: string
  RESULT?: string
}
