/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { CreateGroupRes } from './createGroupRes'

export interface AppResponseCreateGroupRes {
  DATA?: CreateGroupRes
  ERR_CODE?: string
  REASON?: string
  RESULT?: string
}
