/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { TranslateRes } from './translateRes'

export interface AppResponseTranslateRes {
  DATA?: TranslateRes
  ERR_CODE?: string
  REASON?: string
  RESULT?: string
}
