/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { SiteEntity } from './siteEntity'

export interface AppResponseListSiteEntity {
  DATA?: SiteEntity[]
  ERR_CODE?: string
  REASON?: string
  RESULT?: string
}
