/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { SearchRes } from './searchRes'

export interface AppResponseSearchRes {
  DATA?: SearchRes
  ERR_CODE?: string
  REASON?: string
  RESULT?: string
}
