/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ChangeChapterStatusRes } from './changeChapterStatusRes'

export interface AppResponseChangeChapterStatusRes {
  DATA?: ChangeChapterStatusRes
  ERR_CODE?: string
  REASON?: string
  RESULT?: string
}
