/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { DeleteGroupRes } from './deleteGroupRes'

export interface AppResponseDeleteGroupRes {
  DATA?: DeleteGroupRes
  ERR_CODE?: string
  REASON?: string
  RESULT?: string
}
