/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { TargetLocale } from './targetLocale'

export interface AppResponseListTargetLocale {
  DATA?: TargetLocale[]
  ERR_CODE?: string
  REASON?: string
  RESULT?: string
}
