/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ListGroupRes } from './listGroupRes'

export interface AppResponseListGroupRes {
  DATA?: ListGroupRes
  ERR_CODE?: string
  REASON?: string
  RESULT?: string
}
