/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { LocaleRes } from './localeRes'

export interface AppResponseListLocaleRes {
  DATA?: LocaleRes[]
  ERR_CODE?: string
  REASON?: string
  RESULT?: string
}
