/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UserInfRes } from './userInfRes'

export interface AppResponseUserInfRes {
  DATA?: UserInfRes
  ERR_CODE?: string
  REASON?: string
  RESULT?: string
}
