/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UpdateGroupRes } from './updateGroupRes'

export interface AppResponseUpdateGroupRes {
  DATA?: UpdateGroupRes
  ERR_CODE?: string
  REASON?: string
  RESULT?: string
}
