/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ComicDetailRes } from './comicDetailRes'

export interface AppResponseComicDetailRes {
  DATA?: ComicDetailRes
  ERR_CODE?: string
  REASON?: string
  RESULT?: string
}
