/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface BasePermissionsRes {
  CAN_AUTO_TRANSLATE_PS_EXT?: boolean
  CAN_BRING_COMICO?: boolean
  CAN_BRING_KENAZ?: boolean
  CAN_BRING_KILEDEL?: boolean
  CAN_CRAWL?: boolean
  CAN_DELETE_CHAPTER?: boolean
  CAN_DELETE_COMIC?: boolean
  CAN_IMPORT_TRANSLATE_PS_EXT?: boolean
  CAN_OCR?: boolean
  CAN_TRANSLATE?: boolean
  CAN_UPDATE_CHAPTER_NAME?: boolean
  CAN_UPDATE_COMIC_NAME?: boolean
  CAN_UPLOAD?: boolean
}
