/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface ChangeChapterStatusRes {
  CHAPTER_ID?: number
  NEW_STATUS?: string
  UPDATED_AT?: string
}
