/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type ChangeChapterStatusReqSTATUS = typeof ChangeChapterStatusReqSTATUS[keyof typeof ChangeChapterStatusReqSTATUS]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChangeChapterStatusReqSTATUS = {
  READY: 'READY',
  TRANSLATING: 'TRANSLATING',
  SUBMITTED: 'SUBMITTED',
  DONE: 'DONE',
} as const
