/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface ChapterPermissionRes {
  CAN_IMPORT_EXCEL?: boolean
  CAN_PSE_IMPORTING?: boolean
  CAN_TRANSLATE?: boolean
  EXPORT_EXCEL?: boolean
  EXPORT_IMAGE?: boolean
  EXPORT_JSON?: boolean
  EXPORT_PSD?: boolean
  SHOW_DRAW_TEXT_BOX_BTN?: boolean
  SHOW_OCR_BTN?: boolean
  SHOW_TOGGLE_TEXT_BOX_BTN?: boolean
  SHOW_TOGGLE_VISION_BOX_BTN?: boolean
  SHOW_TRANSLATE_BTN?: boolean
  SHOW_TRANSLATE_ENGINE_BTN?: boolean
}
