/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Comic } from './comic'
import type { ChapterImageDetail } from './chapterImageDetail'
import type { Locale } from './locale'
import type { ChapterPermissionRes } from './chapterPermissionRes'

export interface ChapterDetailRes {
  CHAPTER_NAME?: string
  CHAPTER_SITE_ID?: string
  COMIC?: Comic
  CREATED_AT?: string
  DEFAULT_TRANSLATED_LOCALE_CODE?: string
  DEFAULT_TRANSLATED_LOCALE_ID?: number
  DEFAULT_TRANSLATED_LOCALE_ISO2?: string
  DEFAULT_TRANSLATED_LOCALE_NAME?: string
  FROM_SITE?: string
  ID?: number
  IMAGES?: ChapterImageDetail[]
  LOCALES?: Locale[]
  OCR_DETECTED_TEXT_BOX_COUNT?: number
  ORIGINAL_LOCALE_CODE?: string
  ORIGINAL_LOCALE_ID?: number
  ORIGINAL_LOCALE_ISO2?: string
  ORIGINAL_LOCALE_NAME?: string
  OWNER?: string
  PERMISSION?: ChapterPermissionRes
  STATUS?: string
  TRANSLATED_TEXT_BOX_COUNT?: number
  UPDATED_AT?: string
  UPLOAD?: boolean
  VISION_FINISHED?: boolean
}
