/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface CheckNameExistReq {
  COMIC_NAME?: string
  LIST_CHAPTERS_NAME: string[]
  /** @minimum 1 */
  USER_GROUP_ID?: number
}
