/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ChapterEntity } from './chapterEntity'
import type { SiteEntity } from './siteEntity'

export interface ComicEntity {
  CHAPTERS?: ChapterEntity[]
  COMIC_SITE_ID?: string
  CREATED_AT?: string
  EMAIL_OWNER?: string
  ID?: number
  KRATOS_IDENTITY_BINDING_ID?: number
  NAME?: string
  PREVENT_UPDATE_TIME?: boolean
  SITE?: SiteEntity
  UPDATED_AT?: string
  USER_GROUP_ID?: number
}
