/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UserGroupEntity } from './userGroupEntity'
import type { ComicPermissionRes } from './comicPermissionRes'
import type { SiteDetailRes } from './siteDetailRes'

export interface ComicDetailRes {
  COMIC_ID?: number
  COMIC_NAME?: string
  COMIC_SITE_ID?: string
  GROUP?: UserGroupEntity
  PERMISSION?: ComicPermissionRes
  SITE?: SiteDetailRes
}
