/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { FileInfo } from './fileInfo'
import type { ImgTranslated } from './imgTranslated'

export interface ContentTrans {
  CREATED_AT?: string
  FILE_ZIP?: string
  FILES?: FileInfo[]
  IMAGES?: ImgTranslated[]
  JSON?: string
  LANG?: string
  LANG_ID?: number
  ORIGINAL?: boolean
  TEXT_NUM?: number
  UPDATED_AT?: string
}
