/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface CrawlSiteDto {
  CODE?: number
  OCR?: boolean
  SITE_NAME?: string
  TRANSLATE?: boolean
  URL?: string
  VERSION?: string
}
