/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface CreateGroupReq {
  CAN_BRING_COMICO?: boolean
  CAN_BRING_KENAZ?: boolean
  CAN_BRING_KILEDEL?: boolean
  /**
   * @minLength 0
   * @maxLength 60
   */
  GROUP_NAME: string
  /** @minimum 1 */
  LIMIT_COUNT?: number
  LIMITED?: boolean
}
