/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { CreateChapterReqFROMSITE } from './createChapterReqFROMSITE'
import type { ImageOCRInput } from './imageOCRInput'
import type { TextBoxDtoReq } from './textBoxDtoReq'

export interface CreateChapterReq {
  CHAPTER_NAME: string
  CHAPTER_SITE_ID?: string
  COMIC_ID?: number
  COMIC_NAME?: string
  COMIC_SITE_ID?: string
  FROM_SITE?: CreateChapterReqFROMSITE
  IMAGES?: ImageOCRInput[]
  ORIGINAL_TEXT_BOXES?: TextBoxDtoReq[]
  RESIZED_IMAGE?: boolean
  TRANSLATED_TEXT_BOXES?: TextBoxDtoReq[]
  /** @minimum 1 */
  USER_GROUP_ID?: number
}
