/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { TextBoxDtoReq } from './textBoxDtoReq'

export interface CreateDefaultTextBoxesReq {
  ORIGINAL_LOCALE_CODE?: string
  TEXT_BOXES?: TextBoxDtoReq[]
  TRANSLATED_LOCALE_CODE?: string
}
