/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { CreateUpdateChapterDtoCRAWLERDATA } from './createUpdateChapterDtoCRAWLERDATA'
import type { Language } from './language'

export interface CreateUpdateChapterDto {
  CHAPTER_NAME?: string
  CHAPTER_SITE_ID?: string
  COMIC_ID?: number
  COMIC_NAME?: string
  COMIC_SITE_ID?: string
  CRAWLER_DATA?: CreateUpdateChapterDtoCRAWLERDATA
  ID?: number
  IMAGE_COUNT?: number
  MY_SITE_ID?: number
  ORIGIN?: Language
  ORIGINAL_LOCALE?: string
  TRANSLATES?: Language[]
  UPLOAD?: boolean
}
