/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UserGroup } from './userGroup'

export interface CreateGroupRes {
  USER_GROUP?: UserGroup
}
