/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type CreateChapterReqFROMSITE = typeof CreateChapterReqFROMSITE[keyof typeof CreateChapterReqFROMSITE]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateChapterReqFROMSITE = {
  KUAIKANMANHUA: 'KUAIKANMANHUA',
  AC_QQ: 'AC_QQ',
  KANMAN: 'KANMAN',
  IQIYI: 'IQIYI',
  MANMANAPP: 'MANMANAPP',
  MANGA_BILIBILI: 'MANGA_BILIBILI',
  COMIC_NAVER: 'COMIC_NAVER',
  UPLOAD: 'UPLOAD',
  KILEDEL: 'KILEDEL',
  COMICO: 'COMICO',
  KENAZ: 'KENAZ',
} as const
