/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { TextBoxDtoReq } from './textBoxDtoReq'

export interface CreateUpdateTextBoxesRequest {
  CHAPTER_NAME?: string
  COMIC_NAME?: string
  COMIC_SITE_ID?: string
  MY_SITE_ID?: number
  ORIGINAL_LOCALE_CODE?: string
  ORIGINAL_TEXT_BOXES?: TextBoxDtoReq[]
  TRANSLATED_LOCALE_CODE?: string
  TRANSLATED_TEXT_BOXES?: TextBoxDtoReq[]
  UPLOAD?: boolean
}
