/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface CreateIdentityReq {
  EMAIL: string
  GROUP?: string[]
  PASSWORD: string
  PS_FLAG?: boolean
  ROLE: string
}
