/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface DownloadImageReq {
  CHAPTER_NAME?: string
  COMIC_NAME?: string
  URLS?: string[]
}
