/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type ExportQueueTaskResSTATUS = typeof ExportQueueTaskResSTATUS[keyof typeof ExportQueueTaskResSTATUS]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ExportQueueTaskResSTATUS = {
  CREATED: 'CREATED',
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  FINISHED: 'FINISHED',
  CANCEL: 'CANCEL',
  ERROR: 'ERROR',
  RETRYING: 'RETRYING',
} as const
