/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { TrainingChapter } from './trainingChapter'

export interface ExportTrainingResult {
  ITEMS?: TrainingChapter[]
  PAGE?: number
  PER_PAGE?: number
  TOTAL_ITEMS?: number
  TOTAL_PAGES?: number
}
