/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ExportQueueTaskResSTATUS } from './exportQueueTaskResSTATUS'

export interface ExportQueueTaskRes {
  STATUS?: ExportQueueTaskResSTATUS
  TASK_ID?: number
  URL?: string
}
