/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface FileInfo {
  CREATED_AT?: string
  FILE_ID?: number
  UPDATED_AT?: string
  URL?: string
}
