/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface GenPreSignedUrlReq {
  CONTENT_LENGTH?: number
  CONTENT_TYPE?: string
  FILE_NAME?: string
}
