/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface GetListChapterReq {
  CHAPTER_ID?: number
  CHAPTER_NAME?: string
  COMIC_ID?: number
  COMIC_NAME?: string
  CREATED_TIME?: string
  UPDATED_TIME?: string
}
