/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type IdentitySTATE = typeof IdentitySTATE[keyof typeof IdentitySTATE]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IdentitySTATE = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
} as const
