/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { IdentityADDITIONALPROPERTIES } from './identityADDITIONALPROPERTIES'
import type { IdentityCREDENTIALS } from './identityCREDENTIALS'
import type { IdentityMETADATAADMIN } from './identityMETADATAADMIN'
import type { IdentityMETADATAPUBLIC } from './identityMETADATAPUBLIC'
import type { RecoveryIdentityAddress } from './recoveryIdentityAddress'
import type { IdentitySTATE } from './identitySTATE'
import type { IdentityTRAITS } from './identityTRAITS'
import type { VerifiableIdentityAddress } from './verifiableIdentityAddress'

export interface Identity {
  ADDITIONAL_PROPERTIES?: IdentityADDITIONALPROPERTIES
  CREATED_AT?: string
  CREDENTIALS?: IdentityCREDENTIALS
  ID?: string
  METADATA_ADMIN?: IdentityMETADATAADMIN
  METADATA_PUBLIC?: IdentityMETADATAPUBLIC
  ORGANIZATION_ID?: string
  RECOVERY_ADDRESSES?: RecoveryIdentityAddress[]
  SCHEMA_ID?: string
  SCHEMA_URL?: string
  STATE?: IdentitySTATE
  STATE_CHANGED_AT?: string
  TRAITS?: IdentityTRAITS
  UPDATED_AT?: string
  VERIFIABLE_ADDRESSES?: VerifiableIdentityAddress[]
}
