/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { IdentityCredentialsADDITIONALPROPERTIES } from './identityCredentialsADDITIONALPROPERTIES'
import type { IdentityCredentialsCONFIG } from './identityCredentialsCONFIG'
import type { IdentityCredentialsTYPE } from './identityCredentialsTYPE'

export interface IdentityCredentials {
  ADDITIONAL_PROPERTIES?: IdentityCredentialsADDITIONALPROPERTIES
  CONFIG?: IdentityCredentialsCONFIG
  CREATED_AT?: string
  IDENTIFIERS?: string[]
  TYPE?: IdentityCredentialsTYPE
  UPDATED_AT?: string
  VERSION?: number
}
