/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface ImageOCRInput {
  NAME?: string
  RESIZED_URL?: string
  URL?: string
}
