/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface Item {
  CHAPTER_ID?: number
  CHAPTER_NAME?: string
  COMIC_ID?: number
  COMIC_NAME?: string
  CREATED_TIME?: string
  NO?: number
  ORIGINAL_TEXT_BOXES?: number
  TRANSLATE_TEX_BOX_NAME?: string
  TRANSLATE_TEX_BOXES_COUNT?: number
  UPDATED_TIME?: string
}
