/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Image } from './image'

export interface Language {
  ID?: number
  IMAGES?: Image[]
  LOCALE?: string
  TEXT_NUMBER?: number
}
