/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UserGroupEntity } from './userGroupEntity'

export interface ListGroupRes {
  LIST_GROUP?: UserGroupEntity[]
}
