/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface LocaleRes {
  CODE?: string
  ID?: number
  ISO2?: string
  NAME?: string
}
