/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { TextBoxDtoRes } from './textBoxDtoRes'

export interface Locale {
  LOCALE_CODE?: string
  ORIGINAL?: boolean
  TEXT_BOXES?: TextBoxDtoRes[]
}
