/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface LogDtoReq {
  ACCOUNT?: string
  ACTION_TYPE?: number
  CHAPTER_NAME?: string
  COMIC_NAME?: string
  ERROR_CODE?: number
  GETTING_TYPE?: number
  IMAGE_COUNT?: number
  IMAGE_NAME?: string
  RESULT?: number
  TRANSLATED_CHAR_COUNT?: number
  TRANSLATED_TEXT_COUNT?: number
}
