/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface LogReq {
  ACTION_TYPE?: number
  CHAPTER_NAME?: string
  COMIC_NAME?: string
  GETTING_TYPE?: number
  IMAGE_COUNT?: number
  IMAGE_NAME?: string
  RESIZED_IMAGE?: boolean
  RESULT?: number
}
