/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface OcrQueueTaskRes {
  CODE?: number
  MESSAGE?: string
  STATUS?: string
  TASK_ID?: number
}
