/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { RedirectExportImageInput } from './redirectExportImageInput'

export interface RedirectExportChapterInput {
  EXPORT_IMAGE_TYPE?: string
  FROM_SITE?: string
  ID?: number
  IMAGES?: RedirectExportImageInput[]
  NAME?: string
  ORIGINAL_LOCALE?: string
  TARGET_LOCALE?: string
}
