/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { RedirectExportVisionBoxInput } from './redirectExportVisionBoxInput'

export interface RedirectExportTextBoxInput {
  BACKGROUND_COLOR?: string
  BODY_HTML?: string
  CAN_EDIT_BACKGROUND?: boolean
  COMBINED_X?: number
  COMBINED_Y?: number
  FEEDBACK?: boolean
  FONT_FAMILY?: string
  FONT_SIZE?: string
  FONT_STYLE?: string
  FONT_WEIGHT?: string
  HEIGHT?: number
  ID?: number
  IS_FEEDBACK?: boolean
  LOCALE_CODE?: string
  NOTE_TEXT?: string
  ORIGINAL_TEXT?: string
  ORIGINAL_TEXT_BOX_ID?: number
  TEXT?: string
  TEXT_ALIGN?: string
  TEXT_BOX_TYPE?: string
  TEXT_COLOR?: string
  TEXT_DECORATION?: string
  TEXT_DECORATION_COLOR?: string
  TEXT_UNDERLINE_OFFSET?: string
  VISION_BOX?: RedirectExportVisionBoxInput
  WIDTH?: number
}
