/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { RedirectExportTextBoxInput } from './redirectExportTextBoxInput'

export interface RedirectExportImageInput {
  CONFLICT_TEXT_BOX?: boolean
  HEIGHT?: number
  IS_CONFLICT_TEXTBOX?: boolean
  NAME?: string
  TEXT_BOXES?: RedirectExportTextBoxInput[]
  URL?: string
  WIDTH?: number
}
