/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface RenameReq {
  CHAPTER_ID?: number
  CHAPTER_RENAME?: string
  COMIC_ID?: number
  COMIC_RENAME?: string
}
