/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { SearchResItem } from './searchResItem'

export interface SearchRes {
  CURRENT_PAGE?: number
  ITEMS?: SearchResItem[]
  SIZE?: number
  TOTAL_PAGES?: number
  TOTAL_RESULT?: number
}
