/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface SearchComicParams {
  currentPage?: number
  comicName?: string
  userGroupId?: number
  time?: string
  localeCode?: string
  sortName?: string
  sortTime?: string
}
