/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface SearchChapterManagementParams {
  currentPage?: number
  comicId: number
  chapterId?: number
  chapterName?: string
  time?: string
  translateLocaleCode?: string
  sortName?: string
  sortTime?: string
  status?: string
}
