/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface SearchResItem {
  GROUP_NAME?: string
  ID?: number
  LOCALE_CODE?: string
  LOCALE_NAME?: string
  NAME?: string
  TOTAL_CHAPTERS?: number
  UPDATED_AT?: string
}
