/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface TargetLocale {
  CODE?: string
  DEFAULT?: boolean
  ID?: number
  ISO2?: string
  NAME?: string
  TRANSLATE_ENGINE_CODE?: number
}
