/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { VisionBoxDtoRes } from './visionBoxDtoRes'

export interface TextBoxDtoRes {
  BACKGROUND_COLOR?: string
  CAN_EDIT_BACKGROUND?: boolean
  CHAPTER_ID?: number
  COMBINED_X?: number
  COMBINED_Y?: number
  CREATED_AT?: string
  FEEDBACK?: boolean
  FIRST_TRANSLATE_ENGINE_ID?: number
  FONT_FAMILY?: string
  FONT_SIZE?: string
  FONT_STYLE?: string
  FONT_WEIGHT?: string
  HEIGHT?: number
  ID?: number
  LOCALE_CODE?: string
  MANUAL_CREATE_TEXT_BOX?: boolean
  NOTE_TEXT?: string
  ORIGINAL_TEXT_BOX_ID?: number
  PREFIX_INDEX?: string
  ROTATE_DEGREE?: number
  TEXT?: string
  TEXT_ALIGN?: string
  TEXT_BOX_TYPE?: string
  TEXT_COLOR?: string
  TEXT_DECORATION?: string
  TEXT_DECORATION_COLOR?: string
  TEXT_UNDERLINE_OFFSET?: string
  UPDATED_AT?: string
  VISION_BOX?: VisionBoxDtoRes
  WIDTH?: number
}
