/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface TrainingVisionBox {
  COMBINED_X?: number
  COMBINED_Y?: number
  HEIGHT?: number
  TEXT?: string
  WIDTH?: number
}
