/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { TrainingImage } from './trainingImage'

export interface TrainingChapter {
  CHAPTER_ID?: number
  CHAPTER_NAME?: string
  COMIC_NAME?: string
  IMAGES?: TrainingImage[]
  LOCALE_CODE?: string
}
