/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { TrainingVisionBox } from './trainingVisionBox'

export interface TrainingImage {
  HEIGHT?: number
  NAME?: string
  URL?: string
  VISION_BOXES?: TrainingVisionBox[]
  WIDTH?: number
}
