/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { TranslatedTextBoxDTOTEXTBOXTYPE } from './translatedTextBoxDTOTEXTBOXTYPE'

export interface TranslatedTextBoxDTO {
  BACKGROUND_COLOR?: string
  CAN_EDIT_BACKGROUND?: boolean
  COMBINED_X?: number
  COMBINED_Y?: number
  FEEDBACK?: boolean
  FONT_FAMILY?: string
  FONT_SIZE?: string
  HEIGHT?: number
  ID?: number
  LOCALE_CODE?: string
  MANUAL_CREATE_TEXT_BOX?: boolean
  NOTE_TEXT?: string
  ORIGINAL_TEXT_BOX_ID?: number
  ORIGINAL_TEXT_BOX_TEXT?: string
  ROTATE_DEGREE?: number
  TEXT?: string
  TEXT_ALIGN?: string
  TEXT_BOX_TYPE?: TranslatedTextBoxDTOTEXTBOXTYPE
  TEXT_COLOR?: string
  WIDTH?: number
}
