/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface TranslateTextList {
  ORIGINAL_TEXT_BOX_ID?: number
  TRANSLATED_TEXT?: string
  TRANSLATED_TEXT_BOX_ID?: number
}
