/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface TranslateEngineEntity {
  CODE?: number
  CREATED_AT?: string
  ID?: number
  NAME?: string
  UPDATED_AT?: string
}
