/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { TranslateTextList } from './translateTextList'

export interface TranslateRes {
  SOURCE_LOCALE_CODE?: string
  TARGET_LOCALE_CODE?: string
  TRANSLATED_TEXT_LIST?: TranslateTextList[]
}
