/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface TranslatePtsReq {
  END_PROCESS?: boolean
  SOURCE_LOCALE_CODE?: string
  TARGET_LOCALE_CODE?: string
  TEXT_LIST?: string[]
  TRANSLATE_ENGINE_CODE?: number
  USER_GROUP_ID?: number
}
