/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type TranslatedTextBoxDTOTEXTBOXTYPE = typeof TranslatedTextBoxDTOTEXTBOXTYPE[keyof typeof TranslatedTextBoxDTOTEXTBOXTYPE]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TranslatedTextBoxDTOTEXTBOXTYPE = {
  MANUALLY: 'MANUALLY',
  OCR: 'OCR',
  IMPORT_EXCEL: 'IMPORT_EXCEL',
  UPLOAD_PSD: 'UPLOAD_PSD',
  BRING: 'BRING',
  NOTE: 'NOTE',
} as const
