/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { TranslatedText } from './translatedText'

export interface TranslatePtsRes {
  SOURCE_LOCALE_CODE?: string
  TARGET_LOCALE_CODE?: string
  TRANSLATED_TEXT_LIST?: TranslatedText[]
}
