/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface TranslateReq {
  CHAPTER_ID?: number
  GETTING_TYPE_ID?: number
  TRANSLATE_ENGINE_CODE?: number
  TRANSLATE_LOCALE_ID?: number
}
