/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface UpdateComicReq {
  /**
   * @minLength 1
   * @maxLength 150
   */
  COMIC_NAME: string
}
