/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UserGroupWithPermissions } from './userGroupWithPermissions'
import type { BasePermissionsRes } from './basePermissionsRes'

export interface UserInfRes {
  EMAIL?: string
  GROUPS?: UserGroupWithPermissions[]
  ID?: number
  PERMISSION?: BasePermissionsRes
  PS_FLAG?: boolean
  RESIZED_WIDTH?: number
  ROLE?: string
}
