/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface UserUpdatePassReq {
  CONFIRM_NEW_PASSWORD: string
  NEW_PASSWORD: string
  PASSWORD: string
}
