/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type VerifiableIdentityAddressVIA = typeof VerifiableIdentityAddressVIA[keyof typeof VerifiableIdentityAddressVIA]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const VerifiableIdentityAddressVIA = {
  EMAIL: 'EMAIL',
  SMS: 'SMS',
} as const
