/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { VerifiableIdentityAddressADDITIONALPROPERTIES } from './verifiableIdentityAddressADDITIONALPROPERTIES'
import type { VerifiableIdentityAddressVIA } from './verifiableIdentityAddressVIA'

export interface VerifiableIdentityAddress {
  ADDITIONAL_PROPERTIES?: VerifiableIdentityAddressADDITIONALPROPERTIES
  CREATED_AT?: string
  ID?: string
  STATUS?: string
  UPDATED_AT?: string
  VALUE?: string
  VERIFIED?: boolean
  VERIFIED_AT?: string
  VIA?: VerifiableIdentityAddressVIA
}
