/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface VisionBoxDtoRes {
  COMBINED_X?: number
  COMBINED_Y?: number
  DOMINANT_COLOR?: string
  HEIGHT?: number
  ID?: number
  WIDTH?: number
}
